version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: service_catalog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./sqls/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "service_catalog", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s  # Add a start period to give the database time to initialize

  service-catalog:
    build: .
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: service_catalog
      DB_PORT: 5432
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
